name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rhel7-mssql-server:$(date +%s)
    - name: tag the docker image
      run: docker tag  rhel7-mssql-server:$(date +%s) default-openshift-image-registry.mycluster-dal13-b3c-4x16-0143c5dd31acd8e030a1d6e0ab1380e3-0000.us-south.containers.appdomain.cloud/sentinel/rhel7-mssql-server:$(date +%s)
      
